# Generated by Django 3.2.19 on 2023-05-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0002_rename_cliente_id_endereco_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
