# Generated by Django 3.2.19 on 2023-05-11 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0003_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
    ]
