# Generated by Django 3.2.19 on 2023-05-12 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0004_remove_endereco_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='Cliente',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente'),
        ),
    ]
