# Generated by Django 4.1.5 on 2024-04-30 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0002_funcionario_gerente_remove_endereco_cliente_id_and_more'),
        ('appProdutos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('sigla', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'estoque',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'fornecedor',
            },
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='codigo',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
        migrations.CreateModel(
            name='OperacaoEstoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('type', models.CharField(choices=[('ADD', 'Cadastrar'), ('DELETE', 'Remover')], max_length=20)),
                ('quantidade', models.IntegerField()),
                ('estoque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProdutos.estoque')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appClientes.funcionario')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProdutos.produto')),
            ],
            options={
                'verbose_name': 'Operação de Estoque',
                'verbose_name_plural': 'Operações de Estoque',
                'db_table': 'operacao_estoque',
            },
        ),
        migrations.AddField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProdutos.produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProdutos.categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appProdutos.fornecedor'),
        ),
    ]
