# Generated by Django 3.2.16 on 2023-01-13 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProdutos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
