# Generated by Django 3.2.19 on 2023-08-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProdutos', '0002_alter_produto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table=None,
        ),
    ]
