# Generated by Django 4.2.11 on 2024-03-08 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appProdutos', '0003_alter_produto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produto',
            table='produto',
        ),
    ]
